### ISSUE TITLE
Html injection

### ISSUE THREAD

**Issue by cs0m1** [Bradzie/DriftoutIO#61]
Hypertext Markup Language (HTML) injection is a technique used to take advantage of **non-validated input** to modify a web page presented by a web application to its users. Also an attacker can send HTML-fomatted text to modify site content that gets **presented to other users**. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/104421436/200807897-7df42e38-b778-44c9-a681-01e083da7163.png">
this can be achieved by nameing yourself `<span style="color:yellow">RickRoll</span>`
<img width="960" alt="image" src="https://user-images.githubusercontent.com/104421436/200801343-6009e3d2-d2a4-438c-bf08-bac34cf399bf.png">
this can be achieved by nameing yourself `<span><img style="width: 200px; height:auto" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.imgur.com%2FpoCtNRk.gif&f=1&nofb=1&ipt=8292cb15d66691acce55bddd39dd5c8ad62ba691eaf0af4e0d5c6d06f23e3504&ipo=images" alt="rickroll"></span>`

**Comment by Bradzie** [comment]
Maybe carrying out the validation on the client-side wasn't the best idea lol. Thank you for bringing this to my attention, I've released a patch.
